name: metstation
channels:
  - anaconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/free
  - defaults
  - contango
  - ska
  - pytorch
  - mbaijal
  - ezyang
  - gwerbin
  - joshbtn
dependencies:
  - alembic=1.3.2
  - argon2_cffi=19.1.0
  - asn1crypto=1.2.0
  - bcrypt=3.1.7
  - beautifulsoup4=4.8.1
  - blas=1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - chart-studio=1.0.0
  - clang=8.0.1
  - clang_osx-64=4.0.1
  - clangxx=8.0.1
  - clangxx_osx-64=4.0.1
  - click=7.0
  - convertdate=2.1.3
  - cryptography=2.8
  - cycler=0.10.0
  - cython=0.29.13
  - ephem=3.7.7.0
  - fbprophet=0.5
  - flask=1.1.1
  - flask-compress=1.4.0
  - flask-marshmallow=0.10.1
  - flask-migrate=2.4.0
  - flask-script=2.0.6
  - flask-sqlalchemy=2.4.1
  - freetype=2.10.0
  - future=0.18.2
  - holidays=0.9.11
  - html5lib=1.0.1
  - icu=64.2
  - idna=2.8
  - intel-openmp=2019.5
  - itsdangerous=1.1.0
  - jinja2=2.10.3
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libllvm8=8.0.1
  - libpng=1.6.37
  - libpq=11.2
  - libxml2=2.9.10
  - libxslt=1.1.33
  - lunardate=0.2.0
  - lxml=4.4.2
  - mako=1.1.0
  - markupsafe=1.1.1
  - marshmallow=3.2.2
  - marshmallow-sqlalchemy=0.19.0
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mechanize=0.4.5
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.1d
  - pandas=0.25.3
  - passlib=1.7.2
  - patsy=0.5.1
  - pip=19.3.1
  - pkg-config=0.29.2
  - psycopg2=2.8.4
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pysocks=1.7.1
  - pystan=2.17.1.0
  - python=3.7.5
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - pytz=2019.3
  - pyyaml=5.2
  - readline=7.0
  - requests=2.22.0
  - retrying=1.3.3
  - scipy=1.3.1
  - setuptools=42.0.2
  - six=1.13.0
  - soupsieve=1.9.5
  - sqlalchemy=1.3.11
  - sqlite=3.30.1
  - statsmodels=0.10.2
  - tk=8.6.8
  - tornado=6.0.3
  - urllib3=1.25.7
  - virtualenv=16.7.5
  - webencodings=0.5.1
  - werkzeug=0.16.0
  - wheel=0.33.6
  - wtforms=2.2.1
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.0
    - colorlover==0.3.0
    - config==0.4.2
    - cufflinks==0.17.0
    - dash==1.0.0
    - dash-core-components==1.0.0
    - dash-html-components==1.0.0
    - dash-renderer==1.0.0
    - dash-table==4.0.0
    - decorator==4.4.1
    - defusedxml==0.6.0
    - entrypoints==0.3
    - flask-mysql==1.5.0
    - gunicorn==20.0.4
    - importlib-metadata==1.3.0
    - ipykernel==5.1.3
    - ipython==7.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.2
    - jsonschema==3.2.0
    - jupyter-client==5.3.4
    - jupyter-core==4.6.1
    - mistune==0.8.4
    - more-itertools==8.0.2
    - nbconvert==5.6.1
    - nbformat==4.4.0
    - notebook==6.0.2
    - packaging==19.2
    - pandocfilters==1.4.2
    - parso==0.5.2
    - percy==2.0.2
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - plotly==3.10.0
    - pluggy==0.13.1
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.2
    - ptyprocess==0.6.0
    - py==1.8.1
    - pygments==2.5.2
    - pymysql==0.9.3
    - pyrsistent==0.15.6
    - pytest==5.3.2
    - pytest-mock==1.13.0
    - pytest-sugar==0.9.2
    - pyzmq==18.1.1
    - selenium==3.141.0
    - send2trash==1.5.0
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - traitlets==4.3.3
    - waitress==1.4.1
    - wcwidth==0.1.7
    - widgetsnbextension==3.5.1
    - zipp==0.6.0

